services:
  - type: web
    name: rxl-homeopathy
    env: node
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    plan: free
    nodeVersion: 18
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_URL
        value: https://rxl-homeopathy.onrender.com
      - key: NEXTAUTH_SECRET
        generateValue: true
    healthCheckPath: /
    autoDeploy: true
    branch: main
